create or replace trigger ADD_TO_GROUPS
    after insert
    on STUDENT
    for each row
DECLARE
    UAGI NUMBER;
    USGI NUMBER;
    UUGI NUMBER;
    UPGI NUMBER;
    DAGI NUMBER;
    DSGI NUMBER;
    DUGI NUMBER;
    DPGI NUMBER;
    BGI NUMBER;
    BDGI NUMBER;
    SGI NUMBER;
    batchType BATCH.BATCH_TYPE%TYPE;
    studentRoleId Number;
--     currStudent STUDENT%rowtype;
BEGIN

--     currStudent := new;
    studentRoleId := :new.ROLE_ID;
--     DBMS_OUTPUT.PUT_LINE('here');

    SELECT U.ALL_GROUP_ID,  U.STUDENTS_GROUP_ID, U.UGSTUDENTS_GROUP_ID, U.PGSTUDENTS_GROUP_ID,
    D.ALL_GROUP_ID, D.STUDENTS_GROUP_ID, D.UGSTUDENTS_GROUP_ID, D.PGSTUDENTS_GROUP_ID, B.BATCH_GROUP_ID,BD.BATCH_DEPT_GROUP_ID,
    S.SECTION_GROUP_ID, B.BATCH_TYPE
    INTO UAGI, USGI, UUGI, UPGI, DAGI, DSGI, DUGI, DPGI, BGI, BDGI, SGI, batchType
    FROM SECTION S
        JOIN BATCHDEPT BD ON BD.BATCH_ID = S.BATCH_ID AND BD.DEPARTMENT_ID = S.DEPARTMENT_ID
        JOIN BATCH B ON B.BATCH_ID = S.BATCH_ID
        JOIN DEPARTMENT D ON S.DEPARTMENT_ID = D.DEPARTMENT_ID
        JOIN UNIVERSITY U ON U.UNIVERSITY_ID = D.UNIVERSITY_ID
    WHERE S.DEPARTMENT_ID = :new.DEPARTMENT_ID AND S.BATCH_ID = :new.BATCH_ID
      AND S.SECTION_NAME = :new.SECTION_NAME ;

    INSERT ALL
        INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (UAGI, studentRoleId, 'mem')
        INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (USGI, studentRoleId, 'mem')
        INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (DAGI, studentRoleId, 'mem')
        INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (DSGI, studentRoleId, 'mem')
        INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (BGI, studentRoleId, 'mem')
        INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (BDGI, studentRoleId, 'mem')
        INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (SGI, studentRoleId, 'mem')

    SELECT 1 FROM DUAL;
    IF batchType = 'ug' THEN
        INSERT ALL
            INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (UUGI, studentRoleId, 'mem')
            INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (DUGI, studentRoleId, 'mem')

        SELECT 1 FROM DUAL;
    ELSE
        INSERT ALL
            INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (UPGI, studentRoleId, 'mem')
            INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) VALUES (DPGI, studentRoleId, 'mem')
        SELECT 1 FROM DUAL;

    end if;

end;
/

