SELECT P.FIRST_NAME || ' ' || p.LAST_NAME as FULL_NAME, T.ROLE_ID, T.RANK, D.NAME as DEPARTMENT_NAME FROM TEACHER T JOIN ACADEMIC_ROLE AR ON AR.ROLE_ID = T.ROLE_ID
       LEFT OUTER JOIN PERSON P
    on  AR.PERSON_ID = P.PERSON_ID
    LEFT OUTER JOIN DEPARTMENT D on T.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.UNIVERSITY_ID = :uId AND D.DEPARTMENT_ID = :dId