-- INSERT INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE) SELECT GROUP_ID, ROLE_ID, MEMBER_ROLE FROM
--                                                         (SELECT GROUP_ID, 1 as ROLE_ID, 'adm' as MEMBER_ROLE FROM CREATE_GROUP('asdf'));
--
-- DECLARE
--     gr PGROUP%rowtype;
-- BEGIN
--     :gr := CREATE_GROUP('asdf');
--     INSERT INTO GROUP_MEMBER(GROUP_ID, ROLE_ID, MEMBER_ROLE)
--     VALUES (gr.GROUP_ID,:roleId, :mRole );
--
-- end;
--
--
-- SELECT dgt.GROUP_ID as DEPARTMENT_TEACHERS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_Id = dgt.GROUP_ID) as DEPARTMENT_TEACHERS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on C2.CONTENT_ID = POST.CONTENT_ID WHERE C2.GROUP_ID = dgt.GROUP_ID) as DEPARTMENT_TEACHERS_GROUP_POSTS_COUNT,
--        COUNT_INFO.DEPARTMENT_TEACHER_COUNT as DEPARTMENT_TEACHERS_GROUP_MEMBERS_COUNT,
--
--        dga.GROUP_ID as DEPARTMENT_STUDENTS_TEACHERS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_Id = dga.GROUP_ID) as DEPARTMENT_STUDENTS_TEACHERS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on C2.CONTENT_ID = POST.CONTENT_ID WHERE C2.GROUP_ID = dga.GROUP_ID) as DEPARTMENT_STUDENTS_TEACHERS_GROUP_POSTS_COUNT,
--        COUNT_INFO.DEPARTMENT_TEACHER_COUNT + COUNT_INFO.DEPARTMENT_STUDENT_COUNT as DEPARTMENT_STUDENTS_TEACHERS_GROUP_MEMBERS_COUNT,
--
--
--        uga.GROUP_ID as UNIVERSITY_STUDENTS_TEACHERS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_Id = uga.GROUP_ID) as UNIVERSITY_STUDENTS_TEACHERS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on C2.CONTENT_ID = POST.CONTENT_ID WHERE C2.GROUP_ID = uga.GROUP_ID) as UNIVERSITY_STUDENTS_TEACHERS_GROUP_POSTS_COUNT,
--        COUNT_INFO.UNIVERSITY_STUDENT_COUNT + COUNT_INFO.UNIVERSITY_TEACHER_COUNT as UNIVERSITY_STUDENTS_TEACHERS_GROUP_MEMBERS_COUNT,
--
--        ugt.GROUP_ID as UNIVERSITY_TEACHERS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_Id = ugt.GROUP_ID) as UNIVERSITY_TEACHERS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on C2.CONTENT_ID = POST.CONTENT_ID WHERE C2.GROUP_ID = ugt.GROUP_ID) as UNIVERSITY_TEACHERS_GROUP_POSTS_COUNT,
--        COUNT_INFO.UNIVERSITY_TEACHER_COUNT as UNIVERSITY_TEACHERS_GROUP_MEMBERS_COUNT
--
--
-- FROM TEACHER T
--     JOIN (SELECT
--             D3.DEPARTMENT_ID,
--             (SELECT COUNT(*) FROM TEACHER T2 WHERE T2.DEPARTMENT_ID = D3.DEPARTMENT_ID) as DEPARTMENT_TEACHER_COUNT,
--             (SELECT COUNT(*) FROM STUDENT S2 WHERE S2.DEPARTMENT_ID = D3.DEPARTMENT_ID) as DEPARTMENT_STUDENT_COUNT,
--            (SELECT COUNT(*) FROM TEACHER T2 WHERE T2.DEPARTMENT_ID = UNIVERSITY_ID) as UNIVERSITY_TEACHER_COUNT,
--            (SELECT COUNT(*) FROM STUDENT S2 WHERE S2.DEPARTMENT_ID = UNIVERSITY_ID) as UNIVERSITY_STUDENT_COUNT
--             FROM TEACHER T2 JOIN DEPARTMENT D3 on
--             T2.DEPARTMENT_ID = D3.DEPARTMENT_ID WHERE T2.ROLE_ID = :id
--         )
--         COUNT_INFO
--         ON T.DEPARTMENT_ID = COUNT_INFO.DEPARTMENT_ID
--          JOIN DEPARTMENT D on T.DEPARTMENT_ID = D.DEPARTMENT_ID
--          JOIN UNIVERSITY U on D.UNIVERSITY_ID = U.UNIVERSITY_ID
--          LEFT OUTER JOIN PGROUP dgt ON dgt.GROUP_ID = D.TEACHERS_GROUP_ID
--          LEFT OUTER JOIN PGROUP dga On dga.GROUP_ID = D.ALL_GROUP_ID
--          LEFT OUTER JOIN PGROUP ugt ON ugt.GROUP_ID = U.TEACHERS_GROUP_ID
--          LEFT OUTER JOIN PGROUP uga ON uga.GROUP_ID = U.ALL_GROUP_ID
-- WHERE T.ROLE_ID =  2529;
--
--
--
-- SELECT gs.GROUP_ID   as SECTION_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gs.GROUP_ID) as SECTION_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gs.GROUP_ID) as SECTION_GROUP_POST_COUNT,
--        COUNT_INFO.SECTION_STUDENTS_COUNT as SECTION_GROUP_MEMBER_COUNT,
--
--        gbd.GROUP_ID  as BATCH_DEPT_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gbd.GROUP_ID) as BATCH_DEPT_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gbd.GROUP_ID) as BATCH_DEPT_GROUP_POST_COUNT,
--        COUNT_INFO.BATCH_DEPT_STUDENTS_COUNT as BATCH_DEPT_GROUP_MEMBER_COUNT,
--
--        gb.GROUP_ID   as BATCH_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gb.GROUP_ID) as BATCH_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gb.GROUP_ID) as BATCH_GROUP_POST_COUNT,
--        COUNT_INFO.BATCH_STUDENTS_COUNT as BATCH_GROUP_MEMBER_COUNT,
--
--        gds.GROUP_ID  as DEPARTMENT_UG_STUDENTS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gds.GROUP_ID) as DEPARTMENT_UG_STUDENTS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gds.GROUP_ID) as DEPARTMENT_UG_STUDENTS_GROUP_POST_COUNT,
--        COUNT_INFO.DEPARTMENT_UG_STUDENTS_COUNT as DEPARTMENT_UG_STUDENTS_GROUP_MEMBER_COUNT,
--
--        gdsa.GROUP_ID as DEPARTMENT_ALL_STUDENTS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gdsa.GROUP_ID) as DEPARTMENT_ALL_STUDENTS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gdsa.GROUP_ID) as DEPARTMENT_ALL_STUDENTS_GROUP_POST_COUNT,
--        COUNT_INFO.DEPARTMENT_ALL_STUDENTS_COUNT as DEPARTMENT_ALL_STUDENTS_GROUP_MEMBER_COUNT,
--
--        gdst.GROUP_ID as DEPARTMENT_STUDENTS_TEACHERS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gdst.GROUP_ID) as DEPARTMENT_STUDENTS_TEACHERS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gdst.GROUP_ID) as DEPARTMENT_STUDENTS_TEACHERS_GROUP_POST_COUNT,
--        COUNT_INFO.DEPARTMENT_ALL_STUDENTS_COUNT + COUNT_INFO.DEPARTMENT_TEACHERS_COUNT as DEPARTMENT_STUDENTS_TEACHERS_MEMBER_POST_COUNT,
--
--        gus.GROUP_ID  as UNIVERSITY_UG_STUDENTS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gus.GROUP_ID) as UNIVERSITY_UG_STUDENTS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gus.GROUP_ID) as UNIVERSITY_UG_STUDENTS_GROUP_POST_COUNT,
--        COUNT_INFO.UNIVERSITY_UG_STUDENTS_COUNT as UNIVERSITY_UG_STUDENTS_GROUP_MEMBER_COUNT,
--
--        gusa.GROUP_ID as UNIVERSITY_ALL_STUDENTS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gusa.GROUP_ID) as UNIVERSITY_ALL_STUDENTS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gusa.GROUP_ID) as UNIVERSITY_ALL_STUDENTS_GROUP_POST_COUNT,
--        COUNT_INFO.UNIVERSITY_STUDENTS_COUNT as UNIVERSITY_ALL_STUDENTS_GROUP_MEMBER_COUNT,
--
--        gust.GROUP_ID as UNIVERSITY_STUDENTS_TEACHERS_GROUP_ID,
--        (SELECT NAME FROM PGROUP WHERE GROUP_ID = gust.GROUP_ID) as UNIVERSITY_STUDENTS_TEACHERS_GROUP_NAME,
--        (SELECT COUNT(*) FROM POST JOIN CONTENT C2 on POST.CONTENT_ID = C2.CONTENT_ID WHERE C2.GROUP_ID = gust.GROUP_ID) as UNIVERSITY_STUDENTS_TEACHERS_GROUP_POST_COUNT,
--        COUNT_INFO.UNIVERSITY_STUDENTS_COUNT + COUNT_INFO.UNIVERSITY_TEACHERS_COUNT as UNIVERSITY_STUDENTS_TEACHERS_GROUP_MEMBER_COUNT
--
-- FROM STUDENT S
--          JOIN (SELECT S2.DEPARTMENT_ID,
--                 (SELECT COUNT(*)
--                 FROM STUDENT S
--                 WHERE S.SECTION_NAME = S.SECTION_NAME
--                 AND S.BATCH_ID = S.BATCH_ID
--                 AND S.DEPARTMENT_ID = S.DEPARTMENT_ID
--                 )             as SECTION_STUDENTS_COUNT,
--                 (SELECT COUNT(*)
--                 FROM STUDENT S
--                 WHERE S.BATCH_ID = S2.BATCH_ID
--                   AND S.DEPARTMENT_ID = S2.DEPARTMENT_ID
--                )             as BATCH_DEPT_STUDENTS_COUNT,
--                (SELECT COUNT(*)
--                 FROM STUDENT S
--                 WHERE S.BATCH_ID = S2.BATCH_ID
--                )             as BATCH_STUDENTS_COUNT,
--                (SELECT COUNT(*)
--                 FROM STUDENT S
--                 WHERE S.DEPARTMENT_ID = S2.DEPARTMENT_ID
--                )             as DEPARTMENT_ALL_STUDENTS_COUNT,
--                (SELECT COUNT(*)
--                 FROM TEACHER T
--                 WHERE T.DEPARTMENT_ID = S2.DEPARTMENT_ID
--                )             as DEPARTMENT_TEACHERS_COUNT,
--                (SELECT COUNT(*)
--                 FROM TEACHER T
--                          JOIN DEPARTMENT D3 on T.DEPARTMENT_ID = D3.DEPARTMENT_ID
--                 WHERE D3.UNIVERSITY_ID = D2.UNIVERSITY_ID
--                )             as UNIVERSITY_TEACHERS_COUNT,
--                (SELECT COUNT(*)
--                 FROM STUDENT S
--                          JOIN DEPARTMENT D3 on S.DEPARTMENT_ID = D3.DEPARTMENT_ID
--                 WHERE D3.UNIVERSITY_ID = D2.UNIVERSITY_ID
--                )             as UNIVERSITY_STUDENTS_COUNT,
--                (SELECT COUNT(*)
--                 FROM STUDENT S
--                          JOIN BATCH B3 on S.BATCH_ID = B3.BATCH_ID
--                 WHERE B3.UNIVERSITY_ID = D2.UNIVERSITY_ID
--                   AND B3.BATCHOFSTYPE = B2.BATCHOFSTYPE
--                )             as UNIVERSITY_UG_STUDENTS_COUNT,
--
--                (SELECT COUNT(*)
--                 FROM STUDENT S
--                          JOIN BATCH B3 on S.BATCH_ID = B3.BATCH_ID
--                          JOIN DEPARTMENT D4 on S.DEPARTMENT_ID = D4.DEPARTMENT_ID
--                 WHERE D4.DEPARTMENT_ID = S2.DEPARTMENT_ID
--                   AND B3.BATCHOFSTYPE = B2.BATCHOFSTYPE
--                )             as DEPARTMENT_UG_STUDENTS_COUNT
--
--
--                FROM STUDENT S2
--                         JOIN DEPARTMENT D2 on S2.DEPARTMENT_ID = D2.DEPARTMENT_ID
--                         JOIN BATCH B2 ON B2.BATCH_ID = S2.BATCH_ID
--                WHERE S2.ROLE_ID = :id
-- ) COUNT_INFO
--         ON COUNT_INFO.DEPARTMENT_ID = S.DEPARTMENT_ID
--          LEFT OUTER JOIN
--      Section SC
--             ON S.BATCH_ID = SC.BATCH_ID AND S.DEPARTMENT_ID = Sc.DEPARTMENT_ID AND S.SECTION_NAME = Sc.SECTION_NAME
--          LEFT OUTER JOIN BATCHDEPT BD
--              ON S.DEPARTMENT_ID = Bd.DEPARTMENT_ID AND S.BATCH_ID = Bd.BATCH_ID
--          LEFT OUTER JOIN
--      DEPARTMENT D
--          ON D.DEPARTMENT_ID = S.DEPARTMENT_ID
--          LEFT OUTER JOIN
--      UNIVERSITY U
--      ON
--          D.UNIVERSITY_ID = U.UNIVERSITY_ID
--          LEFT OUTER JOIN BATCH B
--                         ON B.BATCH_ID = S.BATCH_ID
--          LEFT OUTER JOIN PGROUP gS
--                          ON gS.GROUP_ID = SC.GROUP_ID
--
--          LEFT OUTER JOIN PGROUP gbd
--                          ON
--                              gbd.GROUP_ID = BD.GROUP_ID
--
--          LEFT OUTER JOIN PGROUP gb
--                          ON gb.group_id = B.GROUP_ID
--          LEFT OUTER JOIN PGROUP gds
--                          ON gds.group_id = D.UGStudents_group_id
--          LEFT OUTER JOIN PGROUP gdsa
--                          ON gdsa.group_id = D.STUDENTS_GROUP_ID
--          LEFT OUTER JOIN PGROUP gdst
--                          ON gdst.group_id = D.all_group_id
--          LEFT OUTER JOIN PGROUP gusa
--                          ON gusa.group_id = U.students_group_id
--          LEFT OUTER JOIN PGROUP gust
--                          ON gust.group_id = U.all_group_id
--          LEFT OUTER JOIN PGROUP gus
--                          ON gus.group_id = U.UGStudents_group_id
-- WHERE S.ROLE_ID = :id;
--
--
--
--
-- SELECT G.GROUP_ID, G.NAME, GM1.MEMBER_ROLE, COUNT(GM2.ROLE_ID) as GROUP_MEMBERS_COUNT,
--        COUNT(P.CONTENT_ID) as GROUP_POSTS_COUNT
--     FROM GROUP_MEMBER GM1
--     JOIN PGROUP G on GM1.GROUP_ID = G.GROUP_ID
--     JOIN GROUP_MEMBER GM2 ON GM2.GROUP_ID = G.GROUP_ID
--     LEFT OUTER JOIN CONTENT C2 on G.GROUP_ID = C2.GROUP_ID
--     LEFT OUTER JOIN POST P on C2.CONTENT_ID = P.CONTENT_ID
--     WHERE GM1.ROLE_ID = :id
-- GROUP BY GM1.ROLE_ID, G.GROUP_ID, G.NAME, GM1.MEMBER_ROLE;
--
--
-- SELECT COM1.CONTENT_ID, COM1.COMMENT_OF, COM1.POSTED_AT, P.FIRST_NAME || ' ' || P.LAST_NAME as USERNAME, COUNT(COM2.CONTENT_ID) as REPLIES,
--        COUNT(V.ROLE_ID) AS UPVOTE,
--        COUNT(V2.ROLE_ID) as DOWNVOTE
--     FROM COMMENT_ COM1
--     JOIN CONTENT CON1 ON COM1.CONTENT_ID = CON1.CONTENT_ID
--     JOIN ACADEMIC_ROLE AR ON Ar.ROLE_ID = CON1.ROLE_ID
--     JOIN PERSON P ON P.PERSON_ID = Ar.PERSON_ID
--     LEFT OUTER JOIN COMMENT_ COM2 ON COM2.COMMENT_OF = CON1.CONTENT_ID
--     LEFT OUTER JOIN VOTE V ON V.CONTENT_ID = COM1.CONTENT_ID AND V.DOWN = 'N'
--     LEFT OUTER JOIN VOTE V2 ON V2.CONTENT_ID = COM1.CONTENT_ID AND V2.DOWN != 'N'
-- WHERE COM1.COMMENT_OF = :cId GROUP BY COM1.CONTENT_ID, COM1.COMMENT_OF, COM1.POSTED_AT, CON1.ROLE_ID, P.FIRST_NAME, P.LAST_NAME;
--
--
--
-- WITH GROUPS AS (
--     SELECT dgt.GROUP_ID as DEPARTMENT_TEACHERS_GROUP_ID,
--            dga.GROUP_ID as DEPARTMENT_STUDENTS_TEACHERS_GROUP_ID,
--            uga.GROUP_ID as UNIVERSITY_STUDENTS_TEACHERS_GROUP_ID,
--            ugt.GROUP_ID as UNIVERSITY_TEACHERS_GROUP_ID,
--            dgt.GROUP_ID as DEPARTMENT_TEACHERS_GROUP_NAME,
--            dga.GROUP_ID as DEPARTMENT_STUDENTS_TEACHERS_GROUP_NAME,
--            uga.GROUP_ID as UNIVERSITY_STUDENTS_TEACHERS_GROUP_NAME,
--            ugt.GROUP_ID as UNIVERSITY_TEACHERS_GROUP_NAME
--
--     FROM TEACHER T
--              JOIN DEPARTMENT D on T.DEPARTMENT_ID = D.DEPARTMENT_ID
--              JOIN UNIVERSITY U on D.UNIVERSITY_ID = U.UNIVERSITY_ID
--              LEFT OUTER JOIN PGROUP dgt ON dgt.GROUP_ID = D.TEACHERS_GROUP_ID
--              LEFT OUTER JOIN PGROUP dga On dga.GROUP_ID = D.ALL_GROUP_ID
--              LEFT OUTER JOIN PGROUP ugt ON ugt.GROUP_ID = U.TEACHERS_GROUP_ID
--              LEFT OUTER JOIN PGROUP uga ON uga.GROUP_ID = U.ALL_GROUP_ID
--     WHERE T.ROLE_ID = :id
-- )
--
-- SELECT C1.CONTENT_ID, C1.GROUP_ID, C1.TEXT, P.TITLE, C1.POSTED_AT,GR.NAME as GROUP_NAME, PER.FIRST_NAME || ' ' || PER.LAST_NAME as USERNAME,
--         COMMENT_COUNT, UPVOTE, DOWNVOTE
--
-- FROM
-- (
--
-- SELECT T.CONTENT_ID, COUNT(COM1.CONTENT_ID) as COMMENT_COUNT, COUNT(V1.CONTENT_ID) as UPVOTE, COUNT(V2.CONTENT_ID) as DOWNVOTE
-- FROM
--      (
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.DEPARTMENT_TEACHERS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.DEPARTMENT_STUDENTS_TEACHERS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.UNIVERSITY_TEACHERS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.UNIVERSITY_STUDENTS_TEACHERS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--      ) T
--
--     LEFT OUTER JOIN COMMENT_ COM1 ON COM1.COMMENT_OF = T.CONTENT_ID
--     LEFT OUTER JOIN VOTE V1 ON V1.CONTENT_ID = T.CONTENT_ID AND V1.DOWN = 'N'
--     LEFT OUTER JOIN VOTE V2 ON V2.CONTENT_ID = T.CONTENT_ID AND V2.DOWN != 'N'
--     GROUP BY T.CONTENT_ID
--     ) CONTENT_IDS
--
-- JOIN CONTENT C1 ON C1.CONTENT_ID = CONTENT_IDS.CONTENT_ID
-- JOIN POST P ON P.CONTENT_ID = C1.CONTENT_ID
-- JOIN PGROUP GR on C1.GROUP_ID = GR.GROUP_ID
-- JOIN ACADEMIC_ROLE AR on C1.ROLE_ID = AR.ROLE_ID
-- JOIN PERSON PER on AR.PERSON_ID = PER.PERSON_ID;
--
--
-- WITH GROUPS as
--          (SELECT gs.name       as SECTION_GROUP_NAME,
--                  gs.GROUP_ID   as SECTION_GROUP_ID,
--                  gbd.name      as BATCH_DEPT_GROUP_NAME,
--                  gbd.GROUP_ID  as BATCH_DEPT_GROUP_ID,
--                  gb.name       as BATCH_GROUP_NAME,
--                  gb.GROUP_ID   as BATCH_GROUP_ID,
--                  gds.name      as DEPARTMENT_UG_STUDENTS_GROUP_NAME,
--                  gds.GROUP_ID  as DEPARTMENT_UG_STUDENTS_GROUP_ID,
--                  gdsa.name     as DEPARTMENT_ALL_STUDENTS_GROUP_NAME,
--                  gdsa.GROUP_ID as DEPARTMENT_ALL_STUDENTS_GROUP_ID,
--
--                  gdst.name     as DEPARTMENT_STUDENTS_TEACHERS_GROUP_NAME,
--                  gdst.GROUP_ID as DEPARTMENT_STUDENTS_TEACHERS_GROUP_ID,
--
--                  gus.name      as UNIVERSITY_UG_STUDENTS_GROUP_NAME,
--                  gus.GROUP_ID  as UNIVERSITY_UG_STUDENTS_GROUP_ID,
--
--                  gusa.name     as UNIVERSITY_ALL_STUDENTS_GROUP_NAME,
--                  gusa.GROUP_ID as UNIVERSITY_ALL_STUDENTS_GROUP_ID,
--
--                  gust.name     as UNIVERSITY_STUDENTS_TEACHERS_GROUP_NAME,
--                  gust.GROUP_ID as UNIVERSITY_STUDENTS_TEACHERS_GROUP_ID
--
--           FROM STUDENT S
--                    LEFT OUTER JOIN
--                Section SC
--                USING (batch_id, department_id, section_name)
--                    LEFT OUTER JOIN BATCHDEPT BD
--                                    USING (BATCH_ID, DEPARTMENT_ID)
--                    LEFT OUTER JOIN
--                DEPARTMENT D
--                USING (DEPARTMENT_ID)
--                    LEFT OUTER JOIN
--                UNIVERSITY U
--                ON
--                    D.UNIVERSITY_ID = U.UNIVERSITY_ID
--                    LEFT OUTER JOIN BATCH B
--                                    USING (BATCH_ID)
--                    LEFT OUTER JOIN PGROUP gS
--                                    ON gS.GROUP_ID = SC.GROUP_ID
--
--                    LEFT OUTER JOIN PGROUP gbd
--                                    ON
--                                        gbd.GROUP_ID = BD.GROUP_ID
--
--                    LEFT OUTER JOIN PGROUP gb
--                                    ON gb.group_id = B.GROUP_ID
--                    LEFT OUTER JOIN PGROUP gds
--                                    ON gds.group_id = D.${type}Students_group_id
--                    LEFT OUTER JOIN PGROUP gdsa
--                                    ON gdsa.group_id = D.STUDENTS_GROUP_ID
--                    LEFT OUTER JOIN PGROUP gdst
--                                    ON gdst.group_id = D.all_group_id
--                    LEFT OUTER JOIN PGROUP gusa
--                                    ON gusa.group_id = U.students_group_id
--                    LEFT OUTER JOIN PGROUP gust
--                                    ON gust.group_id = U.all_group_id
--                    LEFT OUTER JOIN PGROUP gus
--                                    ON gus.group_id = U.${type}Students_group_id
--           WHERE S.ROLE_ID = :id
--          )
--
-- SELECT C1.CONTENT_ID, C1.GROUP_ID, C1.TEXT, P.TITLE, C1.POSTED_AT,GR.NAME as GROUP_NAME, PER.FIRST_NAME || ' ' || PER.LAST_NAME as USERNAME,
--         COMMENT_COUNT, UPVOTE, DOWNVOTE
-- FROM
-- (
-- SELECT T.CONTENT_ID, COUNT(COM1.CONTENT_ID) as COMMENT_COUNT, COUNT(V1.CONTENT_ID) as UPVOTE, COUNT(V2.CONTENT_ID) as DOWNVOTE
-- FROM
--      (
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.SECTION_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.BATCH_DEPT_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.BATCH_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.DEPARTMENT_UG_STUDENTS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.DEPARTMENT_ALL_STUDENTS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.DEPARTMENT_STUDENTS_TEACHERS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.UNIVERSITY_UG_STUDENTS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.UNIVERSITY_ALL_STUDENTS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--          UNION
--          SELECT A.CONTENT_ID
--          FROM GROUPS G
--                   OUTER APPLY(SELECT P.CONTENT_ID
--                               FROM POST P
--                                        JOIN CONTENT C ON C.CONTENT_ID = P.CONTENT_ID
--                               WHERE C.GROUP_ID = G.UNIVERSITY_STUDENTS_TEACHERS_GROUP_ID FETCH NEXT 5 ROWS ONLY) A
--      ) T
--
--     LEFT OUTER JOIN COMMENT_ COM1 ON COM1.COMMENT_OF = T.CONTENT_ID
--     LEFT OUTER JOIN VOTE V1 ON V1.CONTENT_ID = T.CONTENT_ID AND V1.DOWN = 'N'
--     LEFT OUTER JOIN VOTE V2 ON V2.CONTENT_ID = T.CONTENT_ID AND V2.DOWN != 'N'
--     GROUP BY T.CONTENT_ID
-- ) CONTENT_IDS
--
-- JOIN CONTENT C1 ON C1.CONTENT_ID = CONTENT_IDS.CONTENT_ID
-- JOIN POST P ON P.CONTENT_ID = C1.CONTENT_ID
-- JOIN PGROUP GR on C1.GROUP_ID = GR.GROUP_ID
-- JOIN ACADEMIC_ROLE AR on C1.ROLE_ID = AR.ROLE_ID
-- JOIN PERSON PER on AR.PERSON_ID = PER.PERSON_ID;
--

SELECT C.CONTENT_ID, C.TEXT,P.TITLE, C.POSTED_AT, G.GROUP_ID, G.NAME as GROUP_NAME,
       COMMENT_COUNT, UPVOTE_COUNT, DOWNVOTE_COUNT, P2.FIRST_NAME || ' ' || p2.LAST_NAME as POSTED_BY
FROM
(
    SELECT C.CONTENT_ID, COUNT(UNIQUE CMT.CONTENT_ID) as COMMENT_COUNT,
           COUNT(UNIQUE VU.ROLE_ID) as UPVOTE_COUNT,
           COUNT(UNIQUE  VD.ROLE_ID) as DOWNVOTE_COUNT
    FROM GROUP_MEMBER GM
        JOIN PGROUP G on GM.GROUP_ID = G.GROUP_ID
        JOIN CONTENT C ON C.GROUP_ID = G.GROUP_ID
        JOIN POST P ON P.CONTENT_ID = C.CONTENT_ID
        LEFT OUTER JOIN COMMENT_ CMT ON CMT.COMMENT_OF = P.CONTENT_ID
        LEFT OUTER JOIN VOTE VU ON VU.CONTENT_ID = C.CONTENT_ID AND VU.DOWN = 'N'
        LEFT OUTER JOIN VOTE VD ON VD.CONTENT_ID = C.CONTENT_ID AND VD.DOWN = 'Y'

    WHERE GM.ROLE_ID = 3399
    GROUP BY C.CONTENT_ID
    FETCH NEXT 25 ROW ONLY
    ) CONTENT_IDS
JOIN CONTENT C ON C.CONTENT_ID = CONTENT_IDS.CONTENT_ID
JOIN POST P ON P.CONTENT_ID = C.CONTENT_ID
JOIN PGROUP G ON G.GROUP_ID = C.GROUP_ID
JOIN ACADEMIC_ROLE AR on C.ROLE_ID = AR.ROLE_ID
JOIN PERSON P2 on AR.PERSON_ID = P2.PERSON_ID
ORDER BY C.POSTED_AT;




SELECT C.CONTENT_ID, C.TEXT,P.TITLE, C.POSTED_AT, G.GROUP_ID, G.NAME as GROUP_NAME,
COMMENT_COUNT, UPVOTE_COUNT, DOWNVOTE_COUNT, P2.FIRST_NAME || ' ' || p2.LAST_NAME as POSTED_BY
FROM
(
SELECT C.CONTENT_ID, COUNT(UNIQUE CMT.CONTENT_ID) as COMMENT_COUNT,
    COUNT(UNIQUE VU.ROLE_ID) as UPVOTE_COUNT,
    COUNT(UNIQUE  VD.ROLE_ID) as DOWNVOTE_COUNT
    FROM
    CONTENT C
JOIN POST P ON P.CONTENT_ID = C.CONTENT_ID
LEFT OUTER JOIN COMMENT_ CMT ON CMT.COMMENT_OF = P.CONTENT_ID
LEFT OUTER JOIN VOTE VU ON VU.CONTENT_ID = C.CONTENT_ID AND VU.DOWN = 'N'
LEFT OUTER JOIN VOTE VD ON VD.CONTENT_ID = C.CONTENT_ID AND VD.DOWN = 'Y'
WHERE C.CONTENT_ID = :cId AND EXISTS(SELECT * FROM GROUP_MEMBER GM WHERE GM.ROLE_ID = :rId AND GM.GROUP_ID = C.GROUP_ID )
GROUP BY C.CONTENT_ID
) CONTENT_IDS
JOIN CONTENT C ON C.CONTENT_ID = CONTENT_IDS.CONTENT_ID
JOIN POST P ON P.CONTENT_ID = C.CONTENT_ID
JOIN PGROUP G ON G.GROUP_ID = C.GROUP_ID
JOIN ACADEMIC_ROLE AR on C.ROLE_ID = AR.ROLE_ID
JOIN PERSON P2 on AR.PERSON_ID = P2.PERSON_ID;


SELECT COM1.CONTENT_ID, COM1.COMMENT_OF, COM1.POSTED_AT, P.FIRST_NAME || ' ' || P.LAST_NAME as USERNAME, COUNT(COM2.CONTENT_ID) as REPLIES,
COUNT(V.ROLE_ID) AS UPVOTE,
COUNT(V2.ROLE_ID) as DOWNVOTE
FROM COMMENT_ COM1
JOIN CONTENT CON1 ON COM1.CONTENT_ID = CON1.CONTENT_ID
JOIN ACADEMIC_ROLE AR ON Ar.ROLE_ID = CON1.ROLE_ID
JOIN PERSON P ON P.PERSON_ID = Ar.PERSON_ID
LEFT OUTER JOIN COMMENT_ COM2 ON COM2.COMMENT_OF = CON1.CONTENT_ID
LEFT OUTER JOIN VOTE V ON V.CONTENT_ID = COM1.CONTENT_ID AND V.DOWN = 'N'
LEFT OUTER JOIN VOTE V2 ON V2.CONTENT_ID = COM1.CONTENT_ID AND V2.DOWN != 'N'
WHERE COM1.COMMENT_OF = :cId GROUP BY COM1.CONTENT_ID, COM1.COMMENT_OF, COM1.POSTED_AT, CON1.ROLE_ID, P.FIRST_NAME, P.LAST_NAME;
