-- DELETE FROM VOTE;
-- DELETE FROM COMMENT_;
-- DELETE FROM POST;
-- DELETE FROM CONTENT;
--
-- DELETE FROM JOIN_GROUP_REQUEST;
-- DELETE FROM GROUP_MEMBER;
--
-- DELETE FROM STUDENT;
-- DELETE FROM TEACHER;
-- DELETE FROM ACADEMIC_ROLE;
--
-- DELETE FROM SECTION;
-- DELETE FROM BATCHDEPT;
-- DELETE FROM BATCH;
-- DELETE FROM DEPARTMENT;
-- DELETE FROM MANAGEMENT;
-- DELETE FROM UNIVERSITY;
--
-- DELETE FROM PGROUP;
-- DELETE FROM PERSON;


-- BEGIN
--     GENERATE_SAMPLE_DATA('Bangladesh University of Engineering And Technology');
--     GENERATE_SAMPLE_DATA('Khulna University of Engineering And Technology');
--     GENERATE_SAMPLE_DATA('Rajshahi University of Engineering And Technology');
-- end;


--  after generating person

-- UPDATE PERSON SET DISTRICT = null WHERE LENGTH(DISTRICT) > 10;


-- the role ids should be different

-- DECLARE
--     d NUMBER;
-- BEGIN
--     d := CREATE_MANAGEMENT(25643, 25,'adm').MANAGEMENT_ID;
--     d := CREATE_MANAGEMENT(25644, 25,'adm').MANAGEMENT_ID;
--     d := CREATE_MANAGEMENT(25645, 25,'adm').MANAGEMENT_ID;
-- end;



-- UPDATE ACADEMIC_ROLE SET PERSON_ID = NULL WHERE PERSON_ID BETWEEN 25643 AND 25645;

