-- create group_id column in content table
ALTER TABLE CONTENT ADD GROUP_ID number;
UPDATE CONTENT C SET GROUP_ID = (SELECT P.GROUP_ID FROM POST P WHERE P.CONTENT_ID = C.CONTENT_ID );
ALTER TABLE CONTENT ADD CONSTRAINT GROUP_ID_FOREIGN_KEY FOREIGN KEY (GROUP_ID) references PGROUP;
ALTER TABLE POST DROP COLUMN GROUP_ID;